#########################################################
# MCBansProxy Configuration File
# - Main Site: http://mcbans.com
# - Support Desk: http://support.mcbans.com
# - Community: http://forums.mcbans.com
##

# apiKey:
#   Your servers apiKey can be found in your account dashboard http://my.mcbans.com/servers
apiKey: 'd9656a043f5fb9484083ba23347c22041db8460f'

# minRep:
#   Minimum reputation a user may have before being disallowed access to the server.
#   DEFAULT: 3 (-1 to disable)
minRep: 9

# timeout:
#   Timeout (in seconds) value of connecting mcbans API server while player joining the server.
#   DEFAULT: 10 (10 Seconds)
timeout: 10

# isDebug:
#   Enable additional debug messages throughout the plugin
#   DEFAULT: false
isDebug: true

# failsafe:
#   If set to true, disallow access to the server when can't auth players,
#   unavailable mcbans api servers (timeout), internal plugin error etc.
#   DEFAULT: false
failsafe: false